name: scroll_to_index_with_offset
description: scroll to the index of any scrollable widget in Flutter
version: 1.0.7
author: Philip Dolenko <ph.dolenko@gmail.com>
homepage: https://github.com/philipdolenko/scroll-to-index-with-offset
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter